language: cpp
sudo: required
  
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['liblog4cxx10-dev','libboost-program-options-dev','libboost-filesystem-dev','libboost-date-time-dev','libboost-system-dev','libboost-test-dev','libboost-thread-dev','libzmq3-dev']
      env: PYTHONPATH=./lib/python FR_TEST_CONFIG=test_config/fr_test.config FP_TEST_CONFIG=test_config/fp_test.config HDF5_ROOT=$HOME/hdf5-1.8.16
      before_install:
        - bash .travis-install-hdf5.sh
        - sudo apt-get install -y -qq lcov curl
      cache:
        directories:
          - $HOME/hdf5-1.8.16

    - os: osx
      osx_image: xcode7
      compiler: clang
      before_install: 
        - brew update || brew update
        - brew list
        - brew install cmake log4cxx zeromq python homebrew/science/hdf5
        - brew outdated boost || brew upgrade boost 
      env: PYTHONPATH=./lib/python FR_TEST_CONFIG=test_config/fr_test_osx.config FP_TEST_CONFIG=test_config/fp_test_osx.config HDF5_ROOT=/usr/local/


install:
  - mkdir -p build
  - cd build
  - cmake -DHDF5_ROOT=$HDF5_ROOT -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make -j VERBOSE=1
  - HDF5_DIR=$HDF5_ROOT pip install --user h5py
  - pip install --user -r $PYTHONPATH/requirements-travis.txt

script:
  - echo 'Running frameReceiverTest...' && echo -en 'travis_fold:start:fr_test\\r'
  - bin/frameReceiverTest --log_level=all
  - echo -en 'travis_fold:end:fr_test\\r'
#  - python bin/run_integration_test.py --frames=1 --interval=1.0 --timeout=30 --fr_config=$FR_TEST_CONFIG --fp_config=$FP_TEST_CONFIG
  - echo 'Running fileWriterTest...' && echo -en 'travis_fold:start:fw_test\\r'
  - bin/fileWriterTest --log_level=all
  - echo -en 'travis_fold:end:fw_test\\r'

after_success:
  - echo 'Generating coverage report...' && echo -en 'travis_fold:start:coverage\\r'
  - bash ../coverage.sh
  - echo -en 'travis_fold:end:coverage\\r'

notifications:
  slack:
    secure: r8pM4/MZxsJrazTV/mm6WF/qUb+Kz6rOnmNtCS3ggHthH4ISkks9hGGY055cOG3F0AUBzLimPttYFwAn9uPLxTr2VCWUZ9Bx5q4CAILspmzYTJcbFDG+vyiyJEw5b2DzaXto9wcvRMNx5UDGlXXygEvBwpEV7Mgh2jR9jEQKGds=
